export default {
  概況: [
    'dashboard-read'
  ],
  集團概況: [
    'organization-dashboard-read',
    'factory-dashboard-read'
  ],
  快報: [
    'llbroadcast-read',
  ],
  法規: [
    'act-read',
    'act-inquiry',
    'act-update-factory-tag',
  ],
  警示: [
    'alert-read',
    'alert-slove'
  ],
  任務: [
    'task-read',
    'task-create',
    'task-update-creator',
    'task-update-taker',
    'task-update',
    'task-check-taker',
    'task-delete-creator',
    'task-delete-taker',
    'task-delete',
  ],
  承攬商: [
    'contractor-read',
    'contractor-create',
    'contractor-update-creator',
    'contractor-update-owner',
    'contractor-update',
    'contractor-delete-creator',
    'contractor-delete-owner',
    'contractor-delete',
    'contractor-license-read',
    'contractor-license-create',
    'contractor-license-update-creator',
    'contractor-license-update-reminder',
    'contractor-license-update',
    'contractor-license-delete-creator',
    'contractor-license-delete-reminder',
    'contractor-license-delete',
    'contract-read',
    'contract-create',
    'contract-update-creator',
    'contract-update-owner',
    'contract-update',
    'contract-delete-creator',
    'contract-delete-owner',
    'contract-delete',
  ],
  證照: [
    'license-read',
    'license-create',
    'license-update-creator',
    'license-update-reminder',
    'license-update',
    'license-delete-creator',
    'license-delete-reminder',
    'license-delete',
  ],
  教育訓練: [
    'internal-training-read',
    'internal-training-create',
    'internal-training-update-creator',
    'internal-training-update-principal',
    'internal-training-update',
    'internal-training-delete-creator',
    'internal-training-delete-principal',
    'internal-training-delete'
  ],
  風險事件: [
    'event-read',
    'event-create',
    'event-update-creator',
    'event-update-owner',
    'event-update',
    'event-delete-creator',
    'event-delete-owner',
    'event-delete',
  ],
  進場管理: [
    'contractor-enter-record-read',
    'contractor-enter-record-create',
    'contractor-enter-record-update-creator',
    'contractor-enter-record-update-owner',
    'contractor-enter-record-update',
    'contractor-enter-record-delete-creator',
    'contractor-enter-record-delete-owner',
    'contractor-enter-record-delete',
    'exit-checklist',
  ],
  稽核管理: [
    'audit-read',
    'audit-create',
    'audit-update-creator',
    'audit-update-owner',
    'audit-update',
    'audit-delete-creator',
    'audit-delete-owner',
    'audit-delete',
    'audit-record',
    'auditee-record',
  ],
  日常自檢: [
    'checklist-read',
    'checklist-create',
    'checklist-update-creator',
    'checklist-update-owner',
    'checklist-update',
    'checklist-delete-creator',
    'checklist-delete-owner',
    'checklist-delete',
    'checklist-record-checker',
    'checklist-record-manager',
    'checklist-review-record',
    'checklist-sample-record',
  ],
  變動管理: [
    'change-read',
    'change-create',
    'change-update-creator',
    'change-update-owner',
    'change-update',
    'change-delete-creator',
    'change-delete-owner',
    'change-delete',
    'change-record'
  ],
  UserManage: [
    'user-factory-manage',
  ],
  角色管理: [
    'role-read',
    'role-create',
    'role-update-creator',
    'role-update-owner',
    'role-update',
    'role-delete-creator',
    'role-delete-owner',
    'role-delete'
  ],
  工廠管理: [
    'factory-manage'
  ],
  SOS: [
    'sos-create'
  ],
  工廠標籤: [
    'factory-tag-read',
    'factory-tag-create',
    'factory-tag-update',
    'factory-tag-delete',
  ],
  自訂風險: [
    'factory-effect-read',
    'factory-effect-create',
    'factory-effect-udpate',
    'factory-effect-delete'
  ],
  QRcode工具: [
    'qrcode-read',
    'qrcode-create',
    'qrcode-update',
    'qrcode-update-owner',
    'qrcode-delete',
    'qrcode-delete-owner'
  ],
  文件檔案庫: [
    'system-file-read',
    'system-file-delete',
    'first-folder-create',
    'first-folder-update',
    'first-folder-delete',
    'other-folder-create',
    'other-folder-update',
    'other-folder-delete',
    'file-create',
    'file-update',
    'file-delete'
  ],
  內規管理: [
    'guideline-admin-read',
    'guideline-admin-create',
    'guideline-admin-update',
    'guideline-admin-update-owner',
    'guideline-admin-destroy',
    'guideline-admin-destroy-owner',
    'guideline-admin-release',
  ],
  內規: [
    'guideline-read',
    'guideline-history-read'
  ],
}
