import i18next from 'i18next';
export default {
  // scope: [
  //   {
  //     name: i18next.t('概況'),
  //     list: [
  //       {
  //         // id: [
  //         //   'dashboard-show',
  //         //   'system-class-analysis-show',
  //         //   'system-class-analysis-index',
  //         //   'factory-analysis-show',
  //         //   'factory-analysis-index',
  //         // ],
  //         id: [
  //           'dashboard-read',
  //           'user-organization-manage',
  //           'organization-dashboard-read',
  //         ],
  //         name: i18next.t('瀏覽概況'),
  //         key: i18next.t('瀏覽概況'),
  //         locale: [],
  //         sequence: 1,
  //       },
  //     ],
  //   },
  //   {
  //     name: i18next.t('快報'),
  //     list: [
  //       {
  //         // id: ['ll-broadcast-index', 'll-broadcast-show'],
  //         id: ['llbroadcast-read'],
  //         name: i18next.t('瀏覽快報'),
  //         key: i18next.t('瀏覽快報'),
  //         locale: [],
  //         sequence: 1,
  //       },
  //     ],
  //   },
  //   {
  //     name: i18next.t('法規法條'),
  //     list: [
  //       {
  //         // id: [
  //         //   'act-index',
  //         //   'act-show',
  //         //   'article-index',
  //         //   'article-show',
  //         //   'article-version-index',
  //         //   'article-version-show',
  //         //   'act-index-all',
  //         //   'act-index-my',
  //         //   'act-index-my-ids',
  //         //   'act-index-change-export-pdf',
  //         //   'act-index-export-pdf',
  //         // ],
  //         id: [
  //           'act-read',
  //         ],
  //         name: i18next.t('法規瀏覽'),
  //         key: i18next.t('法規瀏覽'),
  //         locale: [],
  //         sequence: 1,
  //       },
  //     ],
  //   },
  //   {
  //     name: i18next.t('警示'),
  //     list: [
  //       {
  //         // id: [
  //         //   'alert-index',
  //         //   'alert-show',
  //         //   'alert-month-index',
  //         //   'alert-month-show',
  //         //   'alert-print-index',
  //         // ],
  //         id: [
  //           'alert-read',
  //         ],
  //         name: i18next.t('瀏覽警示(將收到警示通知)'),
  //         key: i18next.t('瀏覽警示(將收到警示通知)'),
  //         locale: [],
  //         sequence: 1,
  //       },
  //       {
  //         // id: ['alert-index', 'alert-show', 'alert-update', 'alert-unsolve'],
  //         id: ['alert-slove'],
  //         name: '排除/復原警示',
  //         key: '排除/復原警示',
  //         locale: [],
  //         sequence: 2,
  //       },
  //     ],
  //   },
  //   {
  //     name: '任務',
  //     list: [
  //       {
  //         // id: [
  //         //   'task-index',
  //         //   'task-show',
  //         //   'task-month-index',
  //         //   'task-month-show',
  //         //   'task-current-expired-index',
  //         //   'task-total-expired-index',
  //         //   'task-print-index',
  //         //   'task-check',
  //         //   'task-uncheck',
  //         //   'sub-task-index',
  //         //   'sub-task-show',
  //         //   'sub-task-store',
  //         //   'sub-task-update',
  //         //   'sub-task-destroy',
  //         //   'sub-task-index-search',
  //         //   'sub-task-done',
  //         //   'sub-task-undone',
  //         // ],
  //         id: [
  //           'task-read',
  //         ],
  //         name: '瀏覽任務',
  //         key: '瀏覽任務',
  //         locale: [],
  //         sequence: 1,
  //       },
  //       {
  //         // id: [
  //         //   'task-store',
  //         //   'task-check',
  //         //   'task-uncheck',
  //         //   'sub-task-index',
  //         //   'sub-task-show',
  //         //   'sub-task-store',
  //         //   'sub-task-update',
  //         //   'sub-task-destroy',
  //         //   'sub-task-index-search',
  //         //   'sub-task-done',
  //         //   'sub-task-undone',
  //         //   'user-index',
  //         // ],
  //         id: [
  //           'task-create',
  //         ],
  //         name: '新增任務',
  //         key: '新增任務',
  //         locale: [],
  //         sequence: 2,
  //       },
  //       {
  //         // id: [
  //         //   'task-update',
  //         //   'task-check',
  //         //   'task-uncheck',
  //         //   'sub-task-index',
  //         //   'sub-task-show',
  //         //   'sub-task-store',
  //         //   'sub-task-update',
  //         //   'sub-task-destroy',
  //         //   'sub-task-index-search',
  //         //   'sub-task-done',
  //         //   'sub-task-undone',
  //         //   'user-index',
  //         // ],
  //         id: [
  //           'task-update',
  //         ],
  //         name: '編輯任務',
  //         key: '編輯任務',
  //         locale: [],
  //         sequence: 3,
  //       },
  //       {
  //         // id: [
  //         //   'task-destroy',
  //         //   'task-check',
  //         //   'task-uncheck',
  //         //   'sub-task-index',
  //         //   'sub-task-show',
  //         //   'sub-task-store',
  //         //   'sub-task-update',
  //         //   'sub-task-destroy',
  //         //   'sub-task-index-search',
  //         //   'sub-task-done',
  //         //   'sub-task-undone',
  //         // ],
  //         id: [
  //           'task-delete',
  //         ],
  //         name: '刪除任務',
  //         key: '刪除任務',
  //         locale: [],
  //         sequence: 4,
  //       },
  //     ],
  //   },
  //   {
  //     name: '承攬商',
  //     list: [
  //       {
  //         // id: [
  //         //   'contractor-index',
  //         //   'contractor-show',
  //         //   'contractor-customed-type-index',
  //         //   'contractor-customed-type-show',
  //         //   'contractor-customed-type-store',
  //         //   'contractor-customed-type-update',
  //         //   'contractor-customed-type-destroy',
  //         //   'contractor-remark-update',
  //         // ],
  //         id: [
  //           'contractor-read',
  //         ],
  //         name: '瀏覽承攬商',
  //         key: '瀏覽承攬商',
  //         locale: [],
  //         sequence: 1,
  //       },
  //       {
  //         // id: [
  //         //   'contractor-store',
  //         //   'contractor-customed-type-index',
  //         //   'contractor-customed-type-show',
  //         //   'contractor-customed-type-store',
  //         //   'contractor-customed-type-update',
  //         //   'contractor-customed-type-destroy',
  //         //   'user-index',
  //         // ],
  //         id: [
  //           'contractor-create',
  //         ],
  //         name: '新增承攬商',
  //         key: '新增承攬商',
  //         locale: [],
  //         sequence: 2,
  //       },
  //       {
  //         // id: [
  //         //   'contractor-update',
  //         //   'contractor-remark-update',
  //         //   'contractor-customed-type-index',
  //         //   'contractor-customed-type-show',
  //         //   'contractor-customed-type-store',
  //         //   'contractor-customed-type-update',
  //         //   'contractor-customed-type-destroy',
  //         //   'user-index',
  //         // ],
  //         id: [
  //           'contractor-update',
  //         ],
  //         name: '編輯承攬商',
  //         key: '編輯承攬商',
  //         locale: [],
  //         sequence: 3,
  //       },
  //       {
  //         // id: ['contractor-destroy'],
  //         id: ['contractor-delete'],
  //         name: '刪除承攬商',
  //         key: '刪除承攬商',
  //         locale: [],
  //         sequence: 4,
  //       },
  //       {
  //         // id: [
  //         //   'contractor-license-index',
  //         //   'contractor-license-show',
  //         //   'contractor-license-store',
  //         //   'contractor-license-update',
  //         //   'contractor-license-destroy',
  //         //   'contractor-license-index-all',
  //         //   'contractor-license-version-index',
  //         //   'contractor-license-version-show',
  //         //   'contractor-license-version-store',
  //         //   'contractor-license-version-update',
  //         //   'contractor-license-version-destroy',
  //         //   'contractor-license-version-remark-update',
  //         // ],
  //         id: [
  //           'contractor-license-manage',
  //         ],
  //         name: '承攬商資格證',
  //         key: '承攬商資格證',
  //         locale: [],
  //         sequence: 4,
  //       },
  //       {
  //         // id: [
  //         //   'contract-index',
  //         //   'contract-show',
  //         //   'contract-store',
  //         //   'contract-update',
  //         //   'contract-destroy',
  //         // ],
  //         id: [
  //           'contract-manage',
  //         ],
  //         name: '承攬商契約',
  //         key: '承攬商契約',
  //         locale: [],
  //         sequence: 4,
  //       },
  //     ],
  //   },
  //   {
  //     name: '證照',
  //     list: [
  //       {
  //         // id: ['license-index', 'license-show'],
  //         id: ['license-read'],
  //         name: '瀏覽證照',
  //         key: '瀏覽證照',
  //         locale: [],
  //         sequence: 1,
  //       },
  //       {
  //         // id: ['license-store'],
  //         id: ['license-create'],
  //         name: '新增證照',
  //         key: '新增證照',
  //         locale: [],
  //         sequence: 2,
  //       },
  //       {
  //         id: ['license-update'],
  //         name: '編輯證照',
  //         key: '編輯證照',
  //         locale: [],
  //         sequence: 3,
  //       },
  //       {
  //         // id: ['license-destroy'],
  //         id: ['license-delete'],
  //         name: '刪除證照',
  //         key: '刪除證照',
  //         locale: [],
  //         sequence: 4,
  //       },
  //     ],
  //   },
  //   {
  //     name: '教育訓練',
  //     list: [
  //       {
  //         // id: [
  //         //   'internal-training-index',
  //         //   'internal-training-show',
  //         //   'internal-training-print-index',
  //         // ],
  //         id: [
  //           'internal-training-read',
  //         ],
  //         name: '瀏覽教育訓練',
  //         key: '瀏覽教育訓練',
  //         locale: [],
  //         sequence: 1,
  //       },
  //       {
  //         id: ['internal-training-create'],
  //         name: '新增教育訓練',
  //         key: '新增教育訓練',
  //         locale: [],
  //         sequence: 2,
  //       },
  //       {
  //         id: ['internal-training-update'],
  //         name: '編輯教育訓練',
  //         key: '編輯教育訓練',
  //         locale: [],
  //         sequence: 3,
  //       },
  //       {
  //         // id: ['internal-training-destroy'],
  //         id: ['internal-training-delete'],
  //         name: '刪除教育訓練',
  //         key: '刪除教育訓練',
  //         locale: [],
  //         sequence: 4,
  //       },
  //     ],
  //   },
  //   {
  //     name: '風險事件',
  //     list: [
  //       {
  //         // id: [
  //         //   'event-month-index',
  //         //   'event-month-show',
  //         //   'event-index',
  //         //   'event-show',
  //         //   'event-current-add-index',
  //         //   'event-print-index',
  //         // ],
  //         id: [
  //           'event-read',
  //         ],
  //         name: '瀏覽風險事件',
  //         key: '瀏覽風險事件',
  //         locale: [],
  //         sequence: 1,
  //       },
  //       {
  //         // id: ['event-store'],
  //         id: ['event-store'],
  //         name: '新增風險事件',
  //         key: '新增風險事件',
  //         locale: [],
  //         sequence: 2,
  //       },
  //       {
  //         id: ['event-update'],
  //         name: '編輯風險事件',
  //         key: '編輯風險事件',
  //         locale: [],
  //         sequence: 3,
  //       },
  //       {
  //         // id: ['event-destroy'],
  //         id: ['event-delete'],
  //         name: '刪除風險事件',
  //         key: '刪除風險事件',
  //         locale: [],
  //         sequence: 4,
  //       },
  //     ],
  //   },
  //   {
  //     // name: '進廠管理',
  //     list: [
  //       {
  //         // id: [
  //         //   'contractor-enter-record-index',
  //         //   'contractor-enter-record-show',
  //         //   'contractor-enter-record-index-current-add',
  //         //   'contractor-enter-record-index-non-return-total',
  //         //   'contractor-enter-record-remark-update',
  //         //   'contractor-customed-type-index',
  //         //   'contractor-customed-type-show',
  //         //   'contractor-customed-type-store',
  //         //   'contractor-customed-type-update',
  //         //   'contractor-customed-type-destroy',
  //         //   'contractor-enter-record-print-index',
  //         //   'contractor-enter-record-month-index',
  //         //   'contractor-enter-record-month-show',
  //         //   'contractor-enter-record-analysis-index',
  //         //   'contractor-enter-record-analysis-show',
  //         // ],
  //         id: [
  //           'contractor-enter-record-read',
  //         ],
  //         name: '瀏覽進廠管理',
  //         key: '瀏覽進廠管理',
  //         locale: [],
  //         sequence: 1,
  //       },
  //       {
  //         // id: [
  //         //   'contractor-enter-record-store',
  //         //   'contractor-customed-type-index',
  //         //   'contractor-customed-type-show',
  //         //   'contractor-customed-type-store',
  //         //   'contractor-customed-type-update',
  //         //   'contractor-customed-type-destroy',
  //         //   'user-index',
  //         // ],
  //         id: [
  //           'contractor-enter-record-create',
  //         ],
  //         name: '新增進廠管理',
  //         key: '新增進廠管理',
  //         locale: [],
  //         sequence: 2,
  //       },
  //       {
  //         // id: [
  //         //   'contractor-enter-record-update',
  //         //   'contractor-enter-record-remark-update',
  //         //   'contractor-enter-record-exit-check-item-update',
  //         //   'contractor-customed-type-index',
  //         //   'contractor-customed-type-show',
  //         //   'contractor-customed-type-store',
  //         //   'contractor-customed-type-update',
  //         //   'contractor-customed-type-destroy',
  //         //   'user-index',
  //         // ],
  //         id: [
  //           'contractor-enter-record-update',
  //         ],
  //         name: '編輯進廠管理',
  //         key: '編輯進廠管理',
  //         locale: [],
  //         sequence: 3,
  //       },
  //       {
  //         // id: [
  //         //   'contractor-enter-record-destroy',
  //         //   'contractor-customed-type-index',
  //         //   'contractor-customed-type-show',
  //         //   'contractor-customed-type-store',
  //         //   'contractor-customed-type-update',
  //         //   'contractor-customed-type-destroy',
  //         // ],
  //         id: [
  //           'contractor-enter-record-delete',
  //         ],
  //         // name: '刪除進廠管理',
  //         // key: '刪除進廠管理',
  //         locale: [],
  //         sequence: 4,
  //       },
  //       {
  //         // id: [
  //         //   'exit-checklist-index',
  //         //   'exit-checklist-show',
  //         //   'exit-checklist-store',
  //         //   'exit-checklist-update',
  //         //   'exit-checklist-destroy',
  //         //   'exit-check-item-index-index',
  //         //   'exit-check-item-index-show',
  //         //   'exit-check-item-index-store',
  //         //   'exit-check-item-index-update',
  //         //   'exit-check-item-index-destroy',
  //         // ],
  //         id: [
  //           'exit-checklist',
  //         ],
  //         name: '進廠收工作業',
  //         key: '進廠收工作業',
  //         locale: [],
  //         sequence: 5,
  //       },
  //     ],
  //   },
  //   {
  //     name: '稽核管理',
  //     list: [
  //       {
  //         // id: [
  //         //   'audit-index',
  //         //   'audit-show',
  //         //   'audit-version-index',
  //         //   'audit-version-show',
  //         //   'audit-record-index',
  //         //   'audit-record-show',
  //         //   'audit-record-answer-index',
  //         //   'audit-record-answer-show',
  //         //   'audit-record-factory-index',
  //         //   'audit-record-review-remark-update',
  //         //   'audit-request-index',
  //         //   'audit-request-show',
  //         //   'audit-record-answer-index',
  //         //   'audit-record-answer-show',
  //         //   'audit-request-store',
  //         //   'audit-version-index',
  //         //   'audit-version-show',
  //         //   'audit-version-update',
  //         //   'audit-version-store',
  //         // ],
  //         id: [
  //           'audit-read',
  //         ],
  //         name: '瀏覽稽核管理',
  //         key: '瀏覽稽核管理',
  //         locale: [],
  //         sequence: 1,
  //       },
  //       {
  //         // id: [
  //         //   'audit-store',
  //         //   'audit-version-index',
  //         //   'audit-version-show',
  //         //   'audit-version-update',
  //         //   'audit-version-store',
  //         // ],
  //         id: [
  //           'audit-create',
  //         ],
  //         name: '新增稽核管理',
  //         key: '新增稽核管理',
  //         locale: [],
  //         sequence: 2,
  //       },
  //       {
  //         // id: [
  //         //   'audit-update',
  //         //   'audit-version-update',
  //         //   'audit-version-store',
  //         //   'audit-record-review-remark-update',
  //         //   'audit-version-index',
  //         //   'audit-version-show',
  //         //   'audit-version-update',
  //         //   'audit-version-store',
  //         // ],
  //         id: [
  //           'audit-update',
  //         ],
  //         name: '編輯稽核管理',
  //         key: '編輯稽核管理',
  //         locale: [],
  //         sequence: 3,
  //       },
  //       {
  //         // id: ['audit-destroy'],
  //         id: ['audit-delete'],
  //         name: '刪除稽核管理',
  //         key: '刪除稽核管理',
  //         locale: [],
  //         sequence: 4,
  //       },
  //       {
  //         // id: [
  //         //   'audit-record-index',
  //         //   'audit-record-show',
  //         //   'audit-record-update',
  //         //   'audit-record-factory-index',
  //         //   'audit-record-review-remark-update',
  //         //   'audit-record-answer-index',
  //         //   'audit-record-answer-show',
  //         //   'audit-record-answer-update',
  //         //   'audit-record-answer-store',
  //         //   'audit-record-answer-destroy',
  //         //   'audit-request-index',
  //         //   'audit-request-show',
  //         //   'audit-request-update',
  //         //   'audit-request-store',
  //         //   'audit-request-factory-index',
  //         // ],
  //         id: [
  //           'audit-record',
  //         ],
  //         name: '稽核作業：可進行稽核作業、可瀏覽稽核',
  //         key: '稽核作業：可進行稽核作業、可瀏覽稽核',
  //         locale: [],
  //         sequence: 5,
  //       },
  //       {
  //         // id: [
  //         //   'audit-request-factory-index',
  //         //   'audit-record-index',
  //         //   'audit-record-show',
  //         //   'audit-record-update',
  //         //   'audit-record-factory-index',
  //         //   'audit-record-review-remark-update',
  //         //   'audit-record-answer-index',
  //         //   'audit-record-answer-show',
  //         //   'audit-record-answer-update',
  //         //   'audit-record-answer-store',
  //         //   'audit-record-answer-destroy',
  //         //   'audit-request-index',
  //         //   'audit-request-show',
  //         //   'audit-request-update',
  //         //   'audit-request-store',
  //         //   'audit-request-factory-index',
  //         // ],
  //         id: [
  //           'auditee-record',
  //         ],
  //         name: '受稽作業：可回覆稽核結果、可瀏覽稽核',
  //         key: '受稽作業：可回覆稽核結果、可瀏覽稽核',
  //         locale: [],
  //         sequence: 6,
  //       },
  //     ],
  //   },
  //   {
  //     name: '日常自檢',
  //     list: [
  //       {
  //         // id: [
  //         //   'checklist-index',
  //         //   'checklist-index-all',
  //         //   'checklist-index-my',
  //         //   'checklist-index-undo',
  //         //   'checklist-show',
  //         //   'checklist-record-draft-index',
  //         //   'checklist-record-draft-show',
  //         //   'checklist-conclusion-daily-index',
  //         //   'checklist-conclusion-daily-show',
  //         //   'checklist-version-index',
  //         //   'checklist-version-show',
  //         //   'checklist-record-index',
  //         //   'checklist-record-show',
  //         //   'checklist-record-store',
  //         //   'checklist-record-update',
  //         //   'checklist-record-answer-index',
  //         //   'checklist-record-answer-show',
  //         //   'checklist-record-answer-store',
  //         //   'checklist-record-answer-update',
  //         //   'checklist-record-factory-index',
  //         //   'checklist-record-review-remark-update',
  //         //   'checklist-version-question-index',
  //         // ],
  //         id: [
  //           'checklist-read',
  //         ],
  //         name: '瀏覽點檢表',
  //         key: '瀏覽點檢表',
  //         locale: [],
  //         sequence: 1,
  //       },
  //       {
  //         // id: [
  //         //   'checklist-store',
  //         //   'checklist-version-store',
  //         //   'checklist-version-question-index',
  //         // ],
  //         id: [
  //           'checklist-create',
  //         ],
  //         name: '新增點檢表',
  //         key: '新增點檢表',
  //         locale: [],
  //         sequence: 2,
  //       },
  //       {
  //         // id: [
  //         //   'checklist-update',
  //         //   'checklist-version-update',
  //         //   'checklist-version-store',
  //         //   'checklist-record-factory-index',
  //         //   'checklist-record-review-remark-update',
  //         //   'checklist-version-question-index',
  //         //   'checklist-record-answer-index',
  //         //   'checklist-record-answer-show',
  //         //   'checklist-record-answer-store',
  //         //   'checklist-record-answer-update',
  //         // ],
  //         id: [
  //           'checklist-update',
  //         ],
  //         name: '編輯點檢表',
  //         key: '編輯點檢表',
  //         locale: [],
  //         sequence: 3,
  //       },
  //       {
  //         // id: ['checklist-destroy', 'checklist-version-destroy'],
  //         id: ['checklist-delete'],
  //         name: '刪除點檢表',
  //         key: '刪除點檢表',
  //         locale: [],
  //         sequence: 4,
  //       },
  //       {
  //         // id: [
  //         //   'checklist-record-draft-show',
  //         //   'checklist-record-draft-store',
  //         //   'checklist-record-draft-update',
  //         //   'checklist-record-index',
  //         //   'checklist-record-show',
  //         //   'checklist-record-store',
  //         //   'checklist-record-update',
  //         //   'checklist-record-answer-index',
  //         //   'checklist-record-answer-show',
  //         //   'checklist-record-answer-store',
  //         //   'checklist-record-answer-update',
  //         // ],
  //         id: [
  //           'checklist-record',
  //         ],
  //         name: '點檢作業：可進行點檢作業、可瀏覽點檢',
  //         key: '點檢作業：可進行點檢作業、可瀏覽點檢',
  //         locale: [],
  //         sequence: 5,
  //       },
  //       {
  //         // id: [
  //         //   'checklist-record-index',
  //         //   'checklist-record-show',
  //         //   'checklist-record-answer-index',
  //         //   'checklist-record-answer-show',
  //         // ],
  //         id: [
  //           'checklist-review-record',
  //         ],
  //         name: '覆核作業：可覆核點檢結果、可瀏覽點檢',
  //         key: '覆核作業：可覆核點檢結果、可瀏覽點檢',
  //         locale: [],
  //         sequence: 6,
  //       },
  //     ],
  //   },
  //   {
  //     name: '變動管理',
  //     list: [
  //       {
  //         // id: [
  //         //   'change-index',
  //         //   'change-show',
  //         //   'change-index-expired',
  //         //   'change-print-index',
  //         //   'change-version-index',
  //         //   'change-version-show',
  //         //   'change-stop',
  //         //   'change-restart',
  //         //   'change-record-answer-index',
  //         //   'change-record-answer-show',
  //         //   'change-record-answer-store',
  //         //   'change-record-answer-update',
  //         //   'change-record-answer-destroy',
  //         //   'risk-index',
  //         //   'risk-show',
  //         //   'risk-store',
  //         //   'risk-update',
  //         //   'risk-destroy',
  //         //   'risk-version-index',
  //         //   'risk-version-show',
  //         //   'risk-version-store',
  //         //   'risk-version-update',
  //         //   'risk-version-destroy',
  //         //   'change-item-version-index',
  //         //   'change-item-version-show',
  //         //   'change-item-version-store',
  //         //   'change-item-version-update',
  //         //   'change-item-version-destroy',
  //         // ],
  //         id: [
  //           'change-read',
  //         ],
  //         name: '瀏覽變動',
  //         key: '瀏覽變動',
  //         locale: [],
  //         sequence: 1,
  //       },
  //       {
  //         // id: ['change-store', 'change-version-store', 'risk-store'],
  //         id: ['change-create'],
  //         name: '新增變動',
  //         key: '新增變動',
  //         locale: [],
  //         sequence: 2,
  //       },
  //       {
  //         // id: [
  //         //   'change-update',
  //         //   'change-version-store',
  //         //   'change-version-show',
  //         //   'change-version-update',
  //         //   'change-stop',
  //         //   'change-restart',
  //         //   'risk-index',
  //         //   'risk-show',
  //         //   'risk-store',
  //         //   'risk-update',
  //         //   'risk-destroy',
  //         //   'risk-version-index',
  //         //   'risk-version-show',
  //         //   'risk-version-store',
  //         //   'risk-version-update',
  //         //   'risk-version-destroy',
  //         //   'change-item-version-index',
  //         //   'change-item-version-show',
  //         //   'change-item-version-store',
  //         //   'change-item-version-update',
  //         //   'change-item-version-destroy',
  //         // ],
  //         id: [
  //           'change-update',
  //         ],
  //         name: '編輯變動',
  //         key: '編輯變動',
  //         locale: [],
  //         sequence: 3,
  //       },
  //       {
  //         // id: [
  //         //   'change-destroy',
  //         //   'change-version-destroy',
  //         //   'change-stop',
  //         //   'change-restart',
  //         // ],
  //         id: [
  //           'change-delete',
  //         ],
  //         name: '刪除變動管理',
  //         key: '刪除變動管理',
  //         locale: [],
  //         sequence: 4,
  //       },
  //       {
  //         // id: [
  //         //   'change-index',
  //         //   'change-show',
  //         //   'change-version-index',
  //         //   'change-version-show',
  //         //   'change-record-answer-index',
  //         //   'change-record-answer-show',
  //         //   'change-record-answer-store',
  //         //   'change-record-answer-update',
  //         //   'change-record-answer-destroy',
  //         //   'risk-index',
  //         //   'risk-show',
  //         //   'risk-store',
  //         //   'risk-update',
  //         //   'risk-destroy',
  //         //   'risk-version-index',
  //         //   'risk-version-show',
  //         //   'risk-version-store',
  //         //   'risk-version-update',
  //         //   'risk-version-destroy',
  //         // ],
  //         id: [
  //           'change-record',
  //         ],
  //         name: '變動風險評估：可進行評估作業、可瀏覽變動',
  //         key: '變動風險評估：可進行評估作業、可瀏覽變動',
  //         locale: [],
  //         sequence: 5,
  //       },
  //     ],
  //   },
  //   {
  //     name: '成員管理',
  //     list: [
  //       {
  //         // id: [
  //         //   'user-factory-system-subclass-index-index',
  //         //   'user-factory-system-subclass-index-show',
  //         //   'user-factory-system-subclass-index-update',
  //         //   'user-factory-system-subclass-index-store',
  //         //   'user-factory-scope-index',
  //         //   'user-factory-scope-show',
  //         //   'user-factory-scope-update',
  //         //   'user-factory-scope-store',
  //         //   'user-factory-index',
  //         //   'user-destroy',
  //         //   'user-disabled',
  //         //   'user-verify-email',
  //         //   'user-temporary-password',
  //         //   'user-change-name',
  //         // ],
  //         id: [
  //           'user-factory-manage',
  //         ],
  //         name: '成員管理權限',
  //         key: '成員管理權限',
  //         locale: [],
  //         sequence: 1,
  //       },
  //     ],
  //   },
  //   {
  //     name: '角色管理',
  //     list: [
  //       {
  //         // id: [
  //         //   'user-index',
  //         //   'user-show',
  //         //   'user-update',
  //         //   'user-store',
  //         //   'user-destroy',
  //         // ],
  //         id: [
  //           'role-manage',
  //         ],
  //         name: '角色管理權限',
  //         key: '角色管理權限',
  //         locale: [],
  //         sequence: 1,
  //       },
  //     ],
  //   },

  //   {
  //     name: '工廠管理',
  //     list: [
  //       {
  //         // id: [
  //         //   'good-ip-index',
  //         //   'good-ip-show',
  //         //   'good-ip-update',
  //         //   'good-ip-store',
  //         //   'good-ip-destroy',
  //         // ],
  //         id: [
  //           'factory-manage',
  //         ],
  //         name: '工廠管理權限',
  //         key: '工廠管理權限',
  //         locale: [],
  //         sequence: 1,
  //       },
  //     ],
  //   },
  //   {
  //     name: 'SOS',
  //     list: [
  //       {
  //         // id: ['sos-request-store'],
  //         id: ['sos-create'],
  //         name: '建立SOS',
  //         key: '建立SOS',
  //         locale: [],
  //         sequence: 1,
  //       },
  //     ],
  //   },
  // ],
  getFields() {
    // const _roles = {}
    // this.scope.forEach(userRole => {
    //   _roles[userRole.name] = {
    //     label: userRole.name,
    //     type: 'pickerMultiple',
    //     items: userRole.list.map(role => (
    //       {
    //         name: role.name,
    //         value: role.id,
    //       }
    //     ))
    //   }
    // })
    // console.log(_roles,'_roles--');
    return ({
      name: {
        label: i18next.t('角色名稱'),
      },
      sequence: {
        label: i18next.t('排序'),
      },
      // ..._roles,
    })
  },
};
